title: Wha-

author: jans heikkinen
email: jansheikkinen@mail.com

description: >- # this means to ignore newlines until "baseurl:"
  everything of my own making is licensed under
  <a rel="license" href="http://creativecommons.org/publicdomain/zero/1.0/">
    CC0
  </a><br>
  please contact me
  <a href="mailto:jansheikkinen@mail.com">here</a>
  for feedback or corrections


twitter_username: jansheikkinen
github_username:  jansheikkinen

plugins:
  - jekyll-feed
