title: Wha-

author: jans heikkinen
email: jansheikkinen@mail.com

description: >- # this means to ignore newlines until "baseurl:"
  all of my content on this site is licensed under CC0<br>
  other people's work, when used, <i>should</i> be cited<br>
  if anything on this site is incorrect, please
  <a href="mailto:jansheikkinen@mail.com">contact me</a>


twitter_username: jansheikkinen
github_username:  jansheikkinen

plugins:
  - jekyll-feed
